/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

import org.junit.Test;
import static org.junit.Assert.*;

/**
 *
 * @author SDababneh
 */
public class ManageEmployeeTest {
    
    public ManageEmployeeTest() {
    }

    /**
     * Test of main method, of class ManageEmployee.
     * 
     * This was auto generated by the NetBeans IDE.  This is a sample.
     */
    @Test
    public void testMain() {
        System.out.println("main");
        String[] args = null;
        ManageEmployee.main(args);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }

    /**
     * Test of addEmployee method, of class ManageEmployee.
     */
    @Test
    public void testAddEmployee() {
        System.out.println("addEmployee");
        String fname = "";
        String lname = "";
        int salary = 0;
        ManageEmployee instance = new ManageEmployee();
        Integer expResult = null;
        Integer result = instance.addEmployee(fname, lname, salary);
        assertEquals(expResult, result);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }

    /**
     * Test of listEmployees method, of class ManageEmployee.
     */
    @Test
    public void testListEmployees() {
        System.out.println("listEmployees");
        ManageEmployee instance = new ManageEmployee();
        instance.listEmployees();
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }

    /**
     * Test of updateEmployee method, of class ManageEmployee.
     */
    @Test
    public void testUpdateEmployee() {
        System.out.println("updateEmployee");
        Integer EmployeeID = null;
        int salary = 0;
        ManageEmployee instance = new ManageEmployee();
        instance.updateEmployee(EmployeeID, salary);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }

    /**
     * Test of deleteEmployee method, of class ManageEmployee.
     */
    @Test
    public void testDeleteEmployee() {
        System.out.println("deleteEmployee");
        Integer EmployeeID = null;
        ManageEmployee instance = new ManageEmployee();
        instance.deleteEmployee(EmployeeID);
        // TODO review the generated test code and remove the default call to fail.
        fail("The test case is a prototype.");
    }
    
}
